### ISSUE TITLE
How can I use it without https?

### ISSUE THREAD

**Issue by albertcito** [v3nt/docker-wordpress-composer#1]
I'm testing it with [Nextjs](https://nextjs.org/) and [URLQ](https://formidable.com/open-source/urql/docs/advanced/server-side-rendering/#nextjs). But if I try to use `https://myapp.local` in the [Nextjs](https://nextjs.org/docs/basic-features/data-fetching/get-static-props) server side it displays the error `self-signed certificate`.

So I would like to try to connect from Nextjs server side without `https` configuration. I tried to remove it, but it doesn't work to me. I updated the nginx in this way:

```conf
server {
    listen      80;
    listen [::]:80;
    server_name myapp.local;

    root /var/www/html/web;
    index index.php;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass wordpress:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}
```

And setup the `.env` file `WP_HOME=http://myapp.local` but in any case when I go to http://myapp.local it displays `This site can’t be reached` in the browser. May you help me with that please!

**Comment by jonathan88n** [comment]
In your docker-compose.yml file, you probably need to change the nginx service to expose port 80, the config from this repo uses 8901.

for example:


version: '3.6'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'

**Comment by albertcito** [comment]
Hey @jonathan88n  it works perfect. Thank you very much for a very awesome work !!!!!
